# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'chart' do
  
  pod 'Masonry'
  pod 'FMDB'
  pod 'MBProgressHUD'
  pod 'WechatOpenSDK'
  pod 'AFNetworking'
  pod 'JCAlertController'
  pod 'JJStockView'
  pod 'Bugly'

end
